# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_helper}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Sutterer"]
  s.date = %q{2010-06-17}
  s.description = %q{Finally - helpers with proper encapsulation, delegation, interfaces and inheritance!}
  s.email = %q{apotonick@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
     "Rakefile",
     "lib/active_helper.rb",
     "lib/active_helper/base.rb",
     "lib/active_helper/rails.rb",
     "rails/init.rb",
     "test/active_helper_test.rb",
     "test/helpers/helpers.rb",
     "test/rails_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/apotonick/active_helper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Finally - helpers with proper encapsulation, delegation, interfaces and inheritance!}
  s.test_files = [
    "test/rails_test.rb",
     "test/active_helper_test.rb",
     "test/test_helper.rb",
     "test/helpers/helpers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
  end
end

